### PR TITLE
support keywords like type/for without resorting to raw

### LINKED ISSUE #13: Attribute / Keyword Clash
Something I noticed last night was that the module doesn't *seem* to handle clashes between attributes (like label's `for` or input's `type` nicely). They throw saying they're looking for braces, though I'm pretty sure the intention is not to wrap the attr itself in brace syntax in these situations (unless it is and I've got it wrong!).

Test cases...

`<input type={"checkbox"} />`
`<label for={"some-input-ref"} />`

### PR DESCRIPTION
**Pull request by daaku**
fixes #13

### CODE REVIEW

**Comment by daaku** [comment]
I would also argue that support for `r#type` style attributes should be dropped.

**Comment by vpzomtrrfrt** [comment]
As long as this covers all the relevant cases, which it looks like it does, I think we could roll back the r# thing since it wasn't even part of a release yet

**Comment by theashguy** [comment]
Haven't had time to run it yet, but the code looks good.

**Comment by Schniz** [comment]
> I think we could roll back the r# thing since it wasn't even part of a release yet

I agree. Can we roll it back on this PR? 😁

**Comment by daaku** [comment]
I think better to split things into smaller changes - just generally helps imho.. What if this didn't actually work for all cases and we wanted to revert just this change? I'll send another pull request reverting support for `r#` style attributes.

**Comment by Schniz** [comment]
Makes sense. Thanks. I’ll merge it when I will be next to a computer 👨‍💻

**Pull request merged**
